//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderConfirmed
    {
        public int OrderConfirmedId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerMobile { get; set; }
        public string PaymentMode { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> OrderDeliveryUpto { get; set; }
        public Nullable<System.DateTime> OrderDeliveredDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Product Product { get; set; }
    }
}
