//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductSizes = new HashSet<ProductSize>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public System.DateTime ProductAddedDate { get; set; }
        public int ProductCategoryId { get; set; }
        public int ProductAvailability { get; set; }
        public int TotalProductAdded { get; set; }
        public int ProductAdminNotification { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<ProductSize> ProductSizes { get; set; }
    }
}
